int _isupper(char c);
int _isdigit(char c);
int mul(int a, int b);
void _putchar(char c);
void print_numbers(void);
void _putchar(char c);
void print_most_numbers(void);
void more_numbers(void);
void print_line(int n);
void print_diagonal(int n);
